import React from 'react';

// Using a generic 16x16 pixel grid definition for each icon.
// . = transparent, X = #1A1A1A (ink), A = Accent color
const ICONS = {
  home: [
    ".......XX.......",
    "......XXXX......",
    ".....XXAAXX.....",
    "....XXAAAAXX....",
    "...XXAAAAAAXX...",
    "..XXAAAAAAAAXX..",
    ".XXAAAAAAAAAAXX.",
    "XX...XXXXXX...XX",
    "X....XAAAAX....X",
    "X....XAAAAX....X",
    "X....XAAAAX....X",
    "X....XAAAAX....X",
    "X....XXXXXX....X",
    "X..............X",
    "XXXXXXXXXXXXXXXX",
    "................",
  ],
  add: [
    "................",
    "................",
    ".......XX.......",
    ".......XX.......",
    ".......XX.......",
    ".......XX.......",
    ".......XX.......",
    "..XXXXXXXXXXXX..",
    "..XXXXXXXXXXXX..",
    ".......XX.......",
    ".......XX.......",
    ".......XX.......",
    ".......XX.......",
    ".......XX.......",
    "................",
    "................",
  ],
  reports: [
    "................",
    ".XXXXXXXXXXXXX..",
    ".XAAAAAAAAAAAXX.",
    ".XAAAAAAAAAAX.X.",
    ".XAAAAAAAAAAX.X.",
    ".XAAXXXXXAAAX.X.",
    ".XAAAAAAAAAAX.X.",
    ".XAAXXXXXXXXX.X.",
    ".XAAAAAAAAAAX.X.",
    ".XAAXXXXXXXXX.X.",
    ".XAAAAAAAAAAX.X.",
    ".XAAAAAAAAAAX.X.",
    ".XXXXXXXXXXXX.X.",
    "..XXXXXXXXXXXXX.",
    "................",
    "................",
  ],
  lending: [
    "................",
    "....XXXXXXXX....",
    "...XAAAAAAAAX...",
    "...XAAAAAAAAX...",
    "....XXXXXXXX....",
    "......XAAX......",
    ".....XAAAAX.....",
    "....XAAXXAAX....",
    "...XAAX..XAAX...",
    "...XAX....XAX...",
    "...XX......XX...",
    "...X........X...",
    "...X........X...",
    "...X........X...",
    "...X........X...",
    "................",
  ],
  profile: [
    "................",
    "....XXXXXXXX....",
    "...XXAAAAAAXX...",
    "..XXA.AAAA.AXX..",
    "..XXAAAAAAAAXX..",
    "..XXAA.AA.AAXX..",
    "...XXAAAAAAXX...",
    "....XXXXXXXX....",
    "..XXXX....XXXX..",
    ".XAAAAX..XAAAAX.",
    "XAAAAAAXXAAAAAAX",
    "XAAAAAAAAAAAAAAX",
    "XAAAAAAAAAAAAAAX",
    "XAAAAAAAAAAAAAAX",
    "XXXXXXXXXXXXXXXX",
    "................",
  ],
  rupee: [
    "................",
    "..XXXXXXXXXXXX..",
    "..XAAAAAAAAAAX..",
    "..XAAXXXXXXAAX..",
    "..XXXXXXXXXXXX..",
    "..XAAAAAAAAAAX..",
    "..XAAXXXXXXAAX..",
    "..XXXXXXXXAAAAX.",
    "......XAAAAAX...",
    ".....XAAAAAX....",
    "....XAAAAAX.....",
    "...XAAAAAX......",
    "..XAAAAAX.......",
    ".XAAAAAX........",
    ".XXXXXX.........",
    "................",
  ],
  "arrow-up": [
    ".......XX.......",
    "......XXXX......",
    ".....XXAAXX.....",
    "....XXAAAAXX....",
    "...XXAAAAAAXX...",
    "..XXAAAAAAAAXX..",
    ".XXAAAAAAAAAAXX.",
    "XXXXXXXXXXXXXXXX",
    "......XAAX......",
    "......XAAX......",
    "......XAAX......",
    "......XAAX......",
    "......XAAX......",
    "......XAAX......",
    "......XXXX......",
    "................",
  ],
  "arrow-down": [
    "................",
    "......XXXX......",
    "......XAAX......",
    "......XAAX......",
    "......XAAX......",
    "......XAAX......",
    "......XAAX......",
    "......XAAX......",
    "XXXXXXXXXXXXXXXX",
    ".XXAAAAAAAAAAXX.",
    "..XXAAAAAAAAXX..",
    "...XXAAAAAAXX...",
    "....XXAAAAXX....",
    ".....XXAAXX.....",
    "......XXXX......",
    ".......XX.......",
  ],
  handshake: [
    "................",
    "................",
    "................",
    "......XX........",
    ".....XAAX.......",
    "....XAAAAX..XX..",
    "...XAAAAAAXXAAX.",
    "..XAAAAXAAAAAAX.",
    ".XAAAAXXAAAAAAX.",
    ".XAAAAX.XXXXAAX.",
    "..XAAXX....XXXX.",
    "...XX...........",
    "................",
    "................",
    "................",
    "................",
  ],
  chart: [
    "................",
    ".X..............",
    ".X.........XX...",
    ".X.........XX...",
    ".X.........XX...",
    ".X....XX...XX...",
    ".X....XX...XX...",
    ".X....XX...XX...",
    ".X....XX...XX...",
    ".X.XX.XX...XX...",
    ".X.XX.XX...XX...",
    ".X.XX.XX...XX...",
    ".X.XX.XX...XX...",
    ".XXXXXXXXXXXXX..",
    "................",
    "................",
  ],
  cat: [
    "................",
    "..X........X....",
    ".XXX......XXX...",
    ".XAAX....XAAX...",
    ".XAAX....XAAX...",
    "XAAAAAAAAAAAAX..",
    "XAA.AAAAAA.AAX..",
    "XAAAAAAAAAAAAX..",
    "XAAA.A..A.AAAX..",
    "XAAAAAAAAAAAAX..",
    ".XAAAAAAAAAAX...",
    "..XAAAAAAAAX....",
    "..XAAX..XAAX....",
    "..XXXX..XXXX....",
    "................",
    "................",
  ],
  sun: [
    "................",
    ".......XX.......",
    ".......XX.......",
    "....XXXXXXXX....",
    "...XAAAAAAAAX...",
    "..XAAAAAAAAAAX..",
    "..XAAAAAAAAAAX..",
    "XXXAAAAAAAAAAXXX",
    "XXXAAAAAAAAAAXXX",
    "..XAAAAAAAAAAX..",
    "..XAAAAAAAAAAX..",
    "...XAAAAAAAAX...",
    "....XXXXXXXX....",
    ".......XX.......",
    ".......XX.......",
    "................",
  ],
  "money-stack": [
    "................",
    "................",
    "................",
    "....XXXXXXXX....",
    "...XAAAAAAAAX...",
    "..XAAAXAAXAAAX..",
    ".XAAAAAAAAAAAAX.",
    ".XAAXXXXXXAAAX.X",
    ".XAAX....XAAAX.X",
    ".XAAXXXXXXAAAX.X",
    ".XAAAAAAAAAAAAXX",
    ".XXXXXXXXXXXXXX.",
    "................",
    "................",
    "................",
    "................",
  ],
  computer: [
    "................",
    "..XXXXXXXXXXXX..",
    ".XAAAAAAAAAAAAX.",
    ".XAAXAAAAAAAXAX.",
    ".XAAXAAAAAAAXAX.",
    ".XAAXAAAAAAAXAX.",
    ".XAAXAAAAAAAXAX.",
    ".XAAXAAAAAAAXAX.",
    ".XAAXAAAAAAAXAX.",
    ".XAAAAAAAAAAAAX.",
    "..XXXXXXXXXXXX..",
    "....XX....XX....",
    "..XXXXXXXXXXXX..",
    "..XXXXXXXXXXXX..",
    "................",
    "................",
  ],
  // Simple placeholders for the rest, mimicking generic icons
  food: [
    ".......XX.......",
    "......XAAX......",
    ".....XAAAAX.....",
    "....XAAAAAAX....",
    "...XAAAAAAAAX...",
    "..XAAAAAAAAAAX..",
    ".XXXXXXXXXXXXXXXX.",
    "..XAAAAAAAAAAX..",
    "...XXXXXXXXXX...",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
  ],
  travel: [
    "................",
    ".......XX.......",
    "......XAAX......",
    ".....XAAAAX.....",
    "..XXXAAAAAAXXX..",
    ".XAAAAAAAAAAAAX.",
    "XAAAAAAAAAAAAAAX",
    ".......XX.......",
    ".......XX.......",
    ".......XX.......",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
  ],
  housing: [
    ".......XX.......",
    "......XXXX......",
    ".....XXAAXX.....",
    "....XXAAAAXX....",
    "...XXAAAAAAXX...",
    "..XXAAAAAAAAXX..",
    ".XXXXXXXXXXXXXXXX.",
    "....XAAAAAAX....",
    "....XAAAAAAX....",
    "....XAAAAAAX....",
    "....XAAAAAAX....",
    "....XAAAAAAX....",
    "....XXXXXXXX....",
    "................",
    "................",
    "................",
  ],
  fitness: [
    "................",
    "..XX........XX..",
    ".XAAX......XAAX.",
    ".XAAX......XAAX.",
    ".XAAXXXXXXXXAAX.",
    ".XAAAAAAAAAAAAX.",
    ".XAAAAAAAAAAAAX.",
    ".XAAXXXXXXXXAAX.",
    ".XAAX......XAAX.",
    ".XAAX......XAAX.",
    "..XX........XX..",
    "................",
    "................",
    "................",
    "................",
    "................",
  ],
  "self-care": [
    "................",
    "....XX....XX....",
    "...XAAX..XAAX...",
    "..XAAAAXXAAAAX..",
    ".XAAAAAAAAAAAAX.",
    ".XAAAAAAAAAAAAX.",
    ".XAAAAAAAAAAAAX.",
    "..XAAAAAAAAAAX..",
    "...XAAAAAAAAX...",
    "....XAAAAAAX....",
    ".....XAAAAX.....",
    "......XAAX......",
    ".......XX.......",
    "................",
    "................",
    "................",
  ],
  clothing: [
    "................",
    "...XXX....XXX...",
    "..XAAAX..XAAAX..",
    ".XAAAAAXXAAAAAX.",
    "XAAAAAAXXAAAAAAX",
    "XAAXXAAAAAAXXAAX",
    "XAAX.XAAAAX.XAAX",
    "XXX..XAAAAX..XXX",
    ".....XAAAAX.....",
    ".....XAAAAX.....",
    ".....XAAAAX.....",
    ".....XAAAAX.....",
    ".....XXXXXX.....",
    "................",
    "................",
    "................",
  ],
  entertainment: [
    "................",
    ".XXXXXXXXXXXXX..",
    ".XAAAAAAAAAAAXX.",
    ".XAXAXAXAXAXA.X.",
    ".XAAAAAAAAAAX.X.",
    ".XAAAAAAAAAAX.X.",
    ".XAAAAAAAAAAX.X.",
    ".XAAAAAAAAAAX.X.",
    ".XAAAAAAAAAAX.X.",
    ".XAXAXAXAXAXA.X.",
    ".XXXXXXXXXXXX.X.",
    "..XXXXXXXXXXXXX.",
    "................",
    "................",
    "................",
    "................",
  ],
  bills: [
    "................",
    "...XXXXXXXXX....",
    "...XAAAAAAAX....",
    "...XAAXXXXAX....",
    "...XAAAAAAAX....",
    "...XAAXXXXAX....",
    "...XAAAAAAAX....",
    "...XAAXXXXAX....",
    "...XAAAAAAAX....",
    "...XAAXXXXAX....",
    "...XAAAAAAAX....",
    "...XXXXXXXXX....",
    "................",
    "................",
    "................",
    "................",
  ],
  other: [
    "................",
    "................",
    "................",
    "................",
    "....XXX..XXX....",
    "....XAX..XAX....",
    "....XXX..XXX....",
    "................",
    "................",
    "......XXXX......",
    ".....XAAAAX.....",
    "......XXXX......",
    "................",
    "................",
    "................",
    "................",
  ],
};

const PixelIcon = ({ name, size = 16, className = "", accent = "#CE93D8" }) => {
  const grid = ICONS[name] || ICONS["other"];

  return (
    <div
      className={className}
      style={{
        display: "grid",
        gridTemplateColumns: "repeat(16, 1fr)",
        gridTemplateRows: "repeat(16, 1fr)",
        width: `${size}px`,
        height: `${size}px`,
      }}
    >
      {grid.map((row, y) =>
        row.split("").map((cell, x) => {
          let bg = "transparent";
          if (cell === "X") bg = "#1A1A1A";
          if (cell === "A") bg = accent;

          return (
            <div
              key={`${x}-${y}`}
              style={{
                backgroundColor: bg,
                width: "100%",
                height: "100%",
              }}
            />
          );
        })
      )}
    </div>
  );
};

export default PixelIcon;
