import React from 'react';

// Using a generic 16x16 pixel grid definition for each icon.
// . = transparent, X = #1A1A1A (ink), A = Accent color
const ICONS = {
  home: [
    ".......XX.......",
    "......XXXX......",
    ".....XXAAXX.....",
    "....XXAAAAXX....",
    "...XXAAAAAAXX...",
    "..XXAAAAAAAAXX..",
    ".XXAAAAAAAAAAXX.",
    "XX...XXXXXX...XX",
    "X....XAAAAX....X",
    "X....XAAAAX....X",
    "X....XAAAAX....X",
    "X....XAAAAX....X",
    "X....XXXXXX....X",
    "X..............X",
    "XXXXXXXXXXXXXXXX",
    "................",
  ],
  add: [
    "................",
    "................",
    ".......XX.......",
    ".......XX.......",
    ".......XX.......",
    ".......XX.......",
    ".......XX.......",
    "..XXXXXXXXXXXX..",
    "..XXXXXXXXXXXX..",
    ".......XX.......",
    ".......XX.......",
    ".......XX.......",
    ".......XX.......",
    ".......XX.......",
    "................",
    "................",
  ],
  reports: [
    "................",
    ".XXXXXXXXXXXXX..",
    ".XAAAAAAAAAAAXX.",
    ".XAAAAAAAAAAX.X.",
    ".XAAAAAAAAAAX.X.",
    ".XAAXXXXXAAAX.X.",
    ".XAAAAAAAAAAX.X.",
    ".XAAXXXXXXXXX.X.",
    ".XAAAAAAAAAAX.X.",
    ".XAAXXXXXXXXX.X.",
    ".XAAAAAAAAAAX.X.",
    ".XAAAAAAAAAAX.X.",
    ".XXXXXXXXXXXX.X.",
    "..XXXXXXXXXXXXX.",
    "................",
    "................",
  ],
  lending: [
    "................",
    "....XXXXXXXX....",
    "...XAAAAAAAAX...",
    "...XAAAAAAAAX...",
    "....XXXXXXXX....",
    "......XAAX......",
    ".....XAAAAX.....",
    "....XAAXXAAX....",
    "...XAAX..XAAX...",
    "...XAX....XAX...",
    "...XX......XX...",
    "...X........X...",
    "...X........X...",
    "...X........X...",
    "...X........X...",
    "................",
  ],
  profile: [
    "................",
    "....XXXXXXXX....",
    "...XXAAAAAAXX...",
    "..XXA.AAAA.AXX..",
    "..XXAAAAAAAAXX..",
    "..XXAA.AA.AAXX..",
    "...XXAAAAAAXX...",
    "....XXXXXXXX....",
    "..XXXX....XXXX..",
    ".XAAAAX..XAAAAX.",
    "XAAAAAAXXAAAAAAX",
    "XAAAAAAAAAAAAAAX",
    "XAAAAAAAAAAAAAAX",
    "XAAAAAAAAAAAAAAX",
    "XXXXXXXXXXXXXXXX",
    "................",
  ],
  rupee: [
    "................",
    "..XXXXXXXXXXXX..",
    "..XAAAAAAAAAAX..",
    "..XAAXXXXXXAAX..",
    "..XXXXXXXXXXXX..",
    "..XAAAAAAAAAAX..",
    "..XAAXXXXXXAAX..",
    "..XXXXXXXXAAAAX.",
    "......XAAAAAX...",
    ".....XAAAAAX....",
    "....XAAAAAX.....",
    "...XAAAAAX......",
    "..XAAAAAX.......",
    ".XAAAAAX........",
    ".XXXXXX.........",
    "................",
  ],
  "arrow-up": [
    ".......XX.......",
    "......XXXX......",
    ".....XXAAXX.....",
    "....XXAAAAXX....",
    "...XXAAAAAAXX...",
    "..XXAAAAAAAAXX..",
    ".XXAAAAAAAAAAXX.",
    "XXXXXXXXXXXXXXXX",
    "......XAAX......",
    "......XAAX......",
    "......XAAX......",
    "......XAAX......",
    "......XAAX......",
    "......XAAX......",
    "......XXXX......",
    "................",
  ],
  "arrow-down": [
    "................",
    "......XXXX......",
    "......XAAX......",
    "......XAAX......",
    "......XAAX......",
    "......XAAX......",
    "......XAAX......",
    "......XAAX......",
    "XXXXXXXXXXXXXXXX",
    ".XXAAAAAAAAAAXX.",
    "..XXAAAAAAAAXX..",
    "...XXAAAAAAXX...",
    "....XXAAAAXX....",
    ".....XXAAXX.....",
    "......XXXX......",
    ".......XX.......",
  ],
  handshake: [
    "................",
    "................",
    "................",
    "......XX........",
    ".....XAAX.......",
    "....XAAAAX..XX..",
    "...XAAAAAAXXAAX.",
    "..XAAAAXAAAAAAX.",
    ".XAAAAXXAAAAAAX.",
    ".XAAAAX.XXXXAAX.",
    "..XAAXX....XXXX.",
    "...XX...........",
    "................",
    "................",
    "................",
    "................",
  ],
  chart: [
    "................",
    ".X..............",
    ".X.........XX...",
    ".X.........XX...",
    ".X.........XX...",
    ".X....XX...XX...",
    ".X....XX...XX...",
    ".X....XX...XX...",
    ".X....XX...XX...",
    ".X.XX.XX...XX...",
    ".X.XX.XX...XX...",
    ".X.XX.XX...XX...",
    ".X.XX.XX...XX...",
    ".XXXXXXXXXXXXX..",
    "................",
    "................",
  ],
  cat: [
    "................",
    "..X........X....",
    ".XXX......XXX...",
    ".XAAX....XAAX...",
    ".XAAX....XAAX...",
    "XAAAAAAAAAAAAX..",
    "XAA.AAAAAA.AAX..",
    "XAAAAAAAAAAAAX..",
    "XAAA.A..A.AAAX..",
    "XAAAAAAAAAAAAX..",
    ".XAAAAAAAAAAX...",
    "..XAAAAAAAAX....",
    "..XAAX..XAAX....",
    "..XXXX..XXXX....",
    "................",
    "................",
  ],
  sun: [
    "................",
    ".......XX.......",
    ".......XX.......",
    "....XXXXXXXX....",
    "...XAAAAAAAAX...",
    "..XAAAAAAAAAAX..",
    "..XAAAAAAAAAAX..",
    "XXXAAAAAAAAAAXXX",
    "XXXAAAAAAAAAAXXX",
    "..XAAAAAAAAAAX..",
    "..XAAAAAAAAAAX..",
    "...XAAAAAAAAX...",
    "....XXXXXXXX....",
    ".......XX.......",
    ".......XX.......",
    "................",
  ],
  "money-stack": [
    "................",
    "................",
    "................",
    "....XXXXXXXX....",
    "...XAAAAAAAAX...",
    "..XAAAXAAXAAAX..",
    ".XAAAAAAAAAAAAX.",
    ".XAAXXXXXXAAAX.X",
    ".XAAX....XAAAX.X",
    ".XAAXXXXXXAAAX.X",
    ".XAAAAAAAAAAAAXX",
    ".XXXXXXXXXXXXXX.",
    "................",
    "................",
    "................",
    "................",
  ],
  computer: [
    "................",
    "..XXXXXXXXXXXX..",
    ".XAAAAAAAAAAAAX.",
    ".XAAXAAAAAAAXAX.",
    ".XAAXAAAAAAAXAX.",
    ".XAAXAAAAAAAXAX.",
    ".XAAXAAAAAAAXAX.",
    ".XAAXAAAAAAAXAX.",
    ".XAAXAAAAAAAXAX.",
    ".XAAAAAAAAAAAAX.",
    "..XXXXXXXXXXXX..",
    "....XX....XX....",
    "..XXXXXXXXXXXX..",
    "..XXXXXXXXXXXX..",
    "................",
    "................",
  ],
  edit: [
    "................",
    ".............XX.",
    "............XAAX",
    "...........XAAXX",
    "..........XAAXX.",
    ".........XAAXX..",
    "........XAAXX...",
    ".......XAAXX....",
    "......XAAXX.....",
    ".....XAAXX......",
    "....XAAXX.......",
    "...XAAXX........",
    "..XAAXX.........",
    "..XXXX..........",
    "..XX............",
    "................",
  ],
  close: [
    "................",
    "................",
    "..XX........XX..",
    "..XAAX....XAAX..",
    "...XAAX..XAAX...",
    "....XAAXXAAX....",
    ".....XAAAAX.....",
    "......XAAX......",
    ".....XAAAAX.....",
    "....XAAXXAAX....",
    "...XAAX..XAAX...",
    "..XAAX....XAAX..",
    "..XX........XX..",
    "................",
    "................",
    "................",
  ],
  // Simple placeholders for the rest, mimicking generic icons
  food: [
    "................",
    "................",
    "......XXXX......",
    "....XXAAAAXX....",
    "...XAAAAAAAAX...",
    "..XAAAAAAAAAAX..",
    ".XAAAAAAAAAAAAX.",
    "XXXXXXXXXXXXXXXX",
    ".X............X.",
    "XXXXXXXXXXXXXXXX",
    ".XAAAAAAAAAAAAX.",
    "..XAAAAAAAAAAX..",
    "...XXXXXXXXXX...",
    "................",
    "................",
    "................",
  ],
  travel: [
    ".......XX.......",
    "......XAAX......",
    "......XAAX......",
    ".....XAAAAX.....",
    "....XAAAAAAX....",
    "...XAAAAAAAAX...",
    "..XAAAAAAAAAAX..",
    ".XAAAAAAAAAAAAX.",
    "XXXXXXXXXXXXXXXX",
    "......XAAX......",
    "......XAAX......",
    "......XAAX......",
    ".....XAAAAX.....",
    "....XXXXXXXX....",
    "................",
    "................",
  ],
  housing: [
    "................",
    ".......XX.......",
    "......XXXX......",
    ".....XXAAXX.....",
    "....XXAAAAXX....",
    "...XXAAAAAAXX...",
    "..XXAAAAAAAAXX..",
    ".XXAAAAAAAAAAXX.",
    "XXXXXXXXXXXXXXXX",
    "..XAAAAAAAAAAX..",
    "..XAAXXXXXXAAX..",
    "..XAAX....XAAX..",
    "..XAAX....XAAX..",
    "..XAAX....XAAX..",
    "..XXXX....XXXX..",
    "................",
  ],
  fitness: [
    "................",
    "................",
    "..XXXX....XXXX..",
    ".XAAAAX..XAAAAX.",
    ".XAAAAX..XAAAAX.",
    "XXAAAAXXXXAAAAXX",
    "XAAAAAAXXAAAAAAX",
    "XAAAAAAXXAAAAAAX",
    "XAAAAAAXXAAAAAAX",
    "XAAAAAAXXAAAAAAX",
    "XXAAAAXXXXAAAAXX",
    ".XAAAAX..XAAAAX.",
    ".XAAAAX..XAAAAX.",
    "..XXXX....XXXX..",
    "................",
    "................",
  ],
  "self-care": [
    "................",
    "..XXX....XXX....",
    ".XAAAX..XAAAX...",
    "XAAAAAXXAAAAAX.X",
    "XAAAAAAAAAAAAXXX",
    "XAAAAAAAAAAAAX.X",
    "XAAAAAAAAAAAAX..",
    ".XAAAAAAAAAAX...",
    "..XAAAAAAAAX....",
    "...XAAAAAAX.....",
    "....XAAAAX......",
    ".....XAAX.......",
    "......XX........",
    "................",
    "................",
    "................",
  ],
  clothing: [
    "................",
    "..XXX......XXX..",
    ".XAAXX....XXAAX.",
    "XAAAAAXXXXAAAAAX",
    "XAAAAAAXXAAAAAAX",
    "XXAAAAAXXAAAAAXX",
    ".XXAAAAXXAAAAXX.",
    "..XAAAAAAAAAAX..",
    "..XAAAAAAAAAAX..",
    "..XAAAAAAAAAAX..",
    "..XAAAAAAAAAAX..",
    "..XAAAAAAAAAAX..",
    "..XXXXXXXXXXXX..",
    "................",
    "................",
    "................",
  ],
  entertainment: [
    "................",
    "................",
    "................",
    "..XXXXXXXXXXXX..",
    ".XAAAAAAAAAAAAX.",
    ".XAAAAAXXAAAAAX.",
    "XAAXXAAXXAAX.AAX",
    "X.XXXX.XX.A.X.AX",
    "XAAXXAAXXAAX.AAX",
    "XAAAAAAAAAAAAAAX",
    ".XAAXAAAAAAXAAX.",
    "..XX........XX..",
    "................",
    "................",
    "................",
    "................",
  ],
  bills: [
    "................",
    "...XXXXXXXXXX...",
    "...XAAAAAAAAX...",
    "...XAAXXXXAAX...",
    "...XAAAAAAAAX...",
    "...XAAXXXXAAX...",
    "...XAAAAAAAAX...",
    "...XAAXXXXAAX...",
    "...XAAAAAAAAX...",
    "...XAAXXXXAAX...",
    "...XAAAAAAAAX...",
    "...XX.XX.XX.X...",
    "...X..X..X..X...",
    "................",
    "................",
    "................",
  ],
  financial: [
    "................",
    "................",
    "................",
    "..XXXXXXXXXX....",
    ".XAAAAAAAAAAX...",
    "XAAAAAAAAAAAAX..",
    "XAAAAAAAAAAAAXX.",
    "XAAAAXXXXXAAAAX.",
    "XAAAAX...XAAAAX.",
    "XAAAAXXXXXAAAAX.",
    "XAAAAAAAAAAAAXX.",
    "XAAAAAAAAAAAAX..",
    ".XXXXXXXXXXXX...",
    "................",
    "................",
    "................",
  ],
  "unhealthy-habits": [
    "................",
    ".......XX.......",
    "......XAAX......",
    ".....XAAAAX.....",
    "....XAAXXAAX....",
    "...XAAAXXAAAX...",
    "..XAAAAXXAAAAX..",
    ".XAAAAAXXAAAAAX.",
    "XAAAAAAXXAAAAAAX",
    "XAAAAA....AAAAAX",
    "XAAAAA.XX.AAAAAX",
    "XAAAAA.XX.AAAAAX",
    ".XAAAAAAAAAAAAX.",
    "..XXXXXXXXXXXX..",
    "................",
    "................",
  ],
  other: [
    "................",
    "................",
    ".....XXXXXX.....",
    "....XAAAAAAX....",
    "..XXXXXXXXXXXX..",
    ".XAAAAAAAAAAAAX.",
    "XAAXXXXXXXXXXAAX",
    "XAAX........XAAX",
    "XAAX...XX...XAAX",
    "XAAX...XX...XAAX",
    "XAAX........XAAX",
    "XAAX........XAAX",
    "XAAXXXXXXXXXXAAX",
    ".XXXXXXXXXXXXX..",
    "................",
    "................",
  ],
  "deco-star-large": [
    "................",
    ".......XX.......",
    "......XAAX......",
    ".....XAAAAX.....",
    "....XAAAAAAX....",
    "...XXAAAAAAXX...",
    "..XAAAAAAAAAAX..",
    "XXAAAAAAAAAAAAXX",
    "..XAAAAAAAAAAX..",
    "...XXAAAAAAXX...",
    "....XAAAAAAX....",
    ".....XAAAAX.....",
    "......XAAX......",
    ".......XX.......",
    "................",
    "................",
  ],
  "deco-star-small": [
    "................",
    "................",
    "................",
    "................",
    ".......XX.......",
    "......XAAX......",
    ".....XAAAAX.....",
    "....XAAAAAAX....",
    ".....XAAAAX.....",
    "......XAAX......",
    ".......XX.......",
    "................",
    "................",
    "................",
    "................",
    "................",
  ],
  "deco-8bit-star": [
    "................",
    ".......XX.......",
    "......XAAX......",
    ".....XAAAAX.....",
    "....XAAAAAAX....",
    "...XXAAAAAAXX...",
    "..XAAAAAAAAAAX..",
    ".XAAAAAAAAAAAAX.",
    "..XAAAAAAAAAAX..",
    "...XXAAAAAAXX...",
    "....XAAAAAAX....",
    ".....XAAAAX.....",
    "......XAAX......",
    ".......XX.......",
    "................",
    "................",
  ],
  "deco-diamond": [
    "................",
    "................",
    "................",
    "......XXXX......",
    ".....XAAAAX.....",
    "....XAAAAAAX....",
    "...XAAAAAAAAX...",
    "...XAAAAAAAAX...",
    "....XAAAAAAX....",
    ".....XAAAAX.....",
    "......XXXX......",
    "................",
    "................",
    "................",
    "................",
    "................",
  ],
  "deco-heart-sparkle": [
    "................",
    "................",
    "................",
    "....XX....XX....",
    "...XAAX..XAAX...",
    "..XAAAAXXAAAAX..",
    "..XAAAAAAAAAAX..",
    "...XAAAAAAAAX...",
    "....XAAAAAAX....",
    ".....XAAAAX.....",
    "......XAAX......",
    ".......XX.......",
    "................",
    "................",
    "................",
    "................",
  ],
  "deco-cross": [
    "................",
    "................",
    "................",
    ".......XX.......",
    ".......XX.......",
    ".....XXXXXX.....",
    ".....XAAAAX.....",
    ".....XXXXXX.....",
    ".......XX.......",
    ".......XX.......",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
  ],
  "deco-burst": [
    "................",
    "................",
    "................",
    "......XXXX......",
    "....XXXAAXXX....",
    "...XXAAAAAAXX...",
    "...XAAAAAAAAX...",
    "...XAAAAAAAAX...",
    "...XXAAAAAAXX...",
    "....XXXAAXXX....",
    "......XXXX......",
    "................",
    "................",
    "................",
    "................",
    "................",
  ],
  "deco-cluster": [
    "................",
    "................",
    "................",
    "......XXXX......",
    "......XAAX......",
    "......XXXX......",
    "....XXXX..XXXX..",
    "....XAAX..XAAX..",
    "....XXXX..XXXX..",
    "......XXXX......",
    "......XAAX......",
    "......XXXX......",
    "................",
    "................",
    "................",
    "................",
  ],
};

// Ensure uniform category name mapping
const categoryIconMap = {
  "bills": "bills",
  "clothing": "clothing",
  "entertainment": "entertainment",
  "financial": "financial",
  "fitness": "fitness",
  "food": "food",
  "housing & living": "housing",
  "housing-&-living": "housing",
  "other": "other",
  "self care": "self-care",
  "self-care": "self-care",
  "travel": "travel",
  "unhealthy habits": "unhealthy-habits",
  "unhealthy-habits": "unhealthy-habits",
  "deco-star-large": "deco-star-large",
  "deco-star-small": "deco-star-small",
  "deco-8bit-star": "deco-8bit-star",
  "deco-diamond": "deco-diamond",
  "deco-heart-sparkle": "deco-heart-sparkle",
  "deco-cross": "deco-cross",
  "deco-burst": "deco-burst",
  "deco-cluster": "deco-cluster",
};

const PixelIcon = ({ name, size = 16, className = "", accent = "#CE93D8" }) => {
  const normalizedName = typeof name === 'string' ? name.toLowerCase().trim() : '';
  const iconKey = categoryIconMap[normalizedName] || normalizedName;
  const grid = ICONS[iconKey] || ICONS["other"];

  return (
    <div
      className={className}
      style={{
        display: "grid",
        gridTemplateColumns: "repeat(16, 1fr)",
        gridTemplateRows: "repeat(16, 1fr)",
        width: `${size}px`,
        height: `${size}px`,
      }}
    >
      {grid.map((row, y) =>
        row.split("").map((cell, x) => {
          let bg = "transparent";
          if (cell === "X") bg = "#1A1A1A";
          if (cell === "A") bg = accent;

          return (
            <div
              key={`${x}-${y}`}
              style={{
                backgroundColor: bg,
                width: "100%",
                height: "100%",
              }}
            />
          );
        })
      )}
    </div>
  );
};

export default PixelIcon;
